version: "3.8"

volumes:
  identity-service-db_data:
  domain-service-db_data:

services:

  identity-service-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: identity-service-db
    volumes:
      - identity-service-db_data:/var/lib/postgresql/data

  identity-service:
    build:
      context: .
      dockerfile: ./packages/identity-service/Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    environment:
      NODE_ENV: $NODE_ENV
      LOG_LEVEL: $LOG_LEVEL
      PORT: $PORT
      DEBUG_PORT: $DEBUG_PORT
      HOST: identity-service
      DB_PORT: $DB_PORT
      DB_HOST: identity-service-db
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: identity-service-db
      AUTH_AUDIENCE: http://domain-service:8000

    depends_on:
      - identity-service-db

  domain-service-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: domain-service-db
    volumes:
      - domain-service-db_data:/var/lib/postgresql/data

  domain-service:
    build:
      context: .
      dockerfile: ./packages/domain-service/Dockerfile
    ports:
      - "8001:8000"
      - "9230:9229"
    environment:
      NODE_ENV: $NODE_ENV
      LOG_LEVEL: $LOG_LEVEL
      PORT: $PORT
      DEBUG_PORT: $DEBUG_PORT
      HOST: domain-service
      DB_HOST: domain-service-db
      DB_PORT: $DB_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: domain-service-db
      AUTH_SERVER: http://identity-service:8000

    depends_on:
      - domain-service-db
