version: "3.8"

services:
  monorepo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  myapp:
    build:
      context: .
      dockerfile: ./packages/myapp/Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      PORT: 8000
      DEBUG_PORT: 9229
      HOST: localhost
      DB_HOST: myappdb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: myappdb
    depends_on:
      - myappdb

  myappdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myappdb
    volumes:
      - myappdb_data:/var/lib/postgresql/data

volumes:
  myappdb_data:
